CREATE TABLE "events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "uuid" varchar NOT NULL,
  "name" varchar NOT NULL,
  "location" varchar,
  "start_date" timestamp,
  "end_date" timestamp,
  "digital_invitation_url" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now()),
  "deleted_at" timestamp
);

CREATE TABLE "event_user_organizers" (
  "user_id" integer,
  "event_id" integer
);

CREATE TABLE "event_user_guests" (
  "guest_uuid" varchar UNIQUE,
  "event_uuid" varchar,
  "name" varchar NOT NULL,
  "message" text,
  "phone_number" varchar,
  "will_attend_event" varchar(1),
  "qr_code_identifier" varchar
);
